apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp-daemonset
  namespace: mateapp
spec:
  selector:
    matchLabels:
      app: todoapp-daemonset
  template:
    metadata:
      labels:
        app: todoapp-daemonset
    spec:
      containers:
      - name: busybox
        image: yauritux/busybox-curl
        command: ['sh', '-c', 'while true; do curl -sS http://todoapp-clusterip-service/api/health; sleep 5; done']
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
